# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentmap < Formula
  desc "Navigation maps for AI agents in markdown files"
  homepage "https://github.com/RKelln/agentmap"
  version "0.1.0-rc.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RKelln/agentmap/releases/download/v0.1.0-rc.2/agentmap_Darwin_x86_64.tar.gz"
      sha256 "3357efe9aa37c5da77768b97e975b5fad67dfa700153d2b14b6aca65cd9adefc"

      define_method(:install) do
        bin.install "agentmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RKelln/agentmap/releases/download/v0.1.0-rc.2/agentmap_Darwin_arm64.tar.gz"
      sha256 "6c43069a526fcc11945df8f51479f6f7e4e189359c1fb5b0ce4b7c9019270570"

      define_method(:install) do
        bin.install "agentmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RKelln/agentmap/releases/download/v0.1.0-rc.2/agentmap_Linux_x86_64.tar.gz"
      sha256 "caa2dab21bb85fe08197036034ec58601f5eb93505f8657860707f3b81cd064e"
      define_method(:install) do
        bin.install "agentmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RKelln/agentmap/releases/download/v0.1.0-rc.2/agentmap_Linux_arm64.tar.gz"
      sha256 "a04d7400bd5aa5d0c067dcac7980ba01372c3071a5c130557a7f59f4453101ad"
      define_method(:install) do
        bin.install "agentmap"
      end
    end
  end
end
